image:
  repository:  eclipseaerios/aerios-k8s-shim/aerios-k8s-shim:v1.0.0
  pullPolicy: Always

replicas: 1

selectorLabels:
  app: aerios-k8s-shim
  comp: aerios-core
  tier: hlo

service:
  type: ClusterIP
  port: 8085
  targetPort: 8000 

nodeSelector: {}



EnvVar:
  DEV: "false"
  namespace_m2m_clients: "default"
  # Namespace where the wireguard server is deployed,
  # NOTE:if it does not exist (kubectl create ns <namespace_wg>) before deploying the helm chart
  namespace_wg: "default" 
  secret_name_hlo: "keycloak-token-secret-hlo"
  secret_name_cb: "keycloak-token-secret-cb"
  keycloak_url: "https://keycloak.front-research-group.eu" # URL of the keycloak server
  realm_openldap: "NCSRD"   # Keycloak realm for openldap
  client_id_cb: "ContextBroker" # Client ID for the Context Broker
  client_secret_cb: "" # Client Secret for the Context Broker
  client_id_hlo: "HLO" # Client ID for the HLO
  client_secret_hlo: "" # Client secret for the HLO
  url: "http://orion-ld-broker.default.svc.cluster.local" # URL of the Context Broker
  port: "1026" # Port of the Context Broker
  secret_name: "wg-secret-keys"
  private_key_secret_name: "private-key"
  public_key_secret_name: "public-key"
  wireguard_configmap_name: "wg-configmap"
  dnsmasq_configmap_name: "dnsmasq-configmap"
  wireguard_pod_label: "app=wireguard"
  overlay_subnet: "10.13.13.0"
